"""Troubleshooting content used by build_page.py.

Text values may contain simple HTML (<code>, <strong>); keep '<' and '&' escaped otherwise.
"""

# ---------------------------------------------------------------- Troubleshooting
CHECKLIST = [
    "<strong>Read the first error line.</strong> It usually names the problem: a missing file, a certificate, a hostname, a timeout or authentication.",
    "<strong>Check the inputs.</strong> Echo <code>REDIS_HOST</code> and <code>REDIS_PORT</code> and confirm they point at the TLS port of your database.",
    "<strong>Check the files.</strong> All three exist, are readable, and are in PEM format (text starting with <code>-----BEGIN</code>).",
    "<strong>Check certificate dates.</strong> An expired or not-yet-valid certificate fails every time.",
    "<strong>Check the chain.</strong> The CA file must be the CA that signed the <em>server</em> certificate, and the client certificate must be signed by a CA the server trusts.",
    "<strong>Check the key.</strong> The private key must belong to the client certificate.",
    "<strong>Test outside the app</strong> with <code>openssl s_client</code> and <code>redis-cli</code> (commands below). If those fail too, the problem is the certificates, network or server, not your code.",
    "<strong>Check authentication last.</strong> Errors such as <code>WRONGPASS</code> or <code>NOAUTH</code> mean TLS already worked.",
]

# [symptom, likely cause, what to do]
GENERAL_ERRORS = [
    ["<code>REDIS_HOST must be set</code> / <code>Redis host is required</code> / <code>REDIS_CLIENT_CERT and REDIS_CLIENT_KEY must be set together</code>",
     "The examples no longer have a built-in host or certificate paths, and a client certificate needs its key (and the other way round).",
     "Set <code>REDIS_HOST</code> (and <code>REDIS_PORT</code> if it is not 443), and give <em>both</em> <code>REDIS_CLIENT_CERT</code> and <code>REDIS_CLIENT_KEY</code>, or neither."],
    ["Connection is closed or reset right away, protocol errors, or a timeout although the host and port are correct",
     "The database needs TLS but the example connected without it. TLS turns on only when you supply a certificate (or set <code>REDIS_TLS=true</code> / <code>REDIS_USE_SSL=1</code>).",
     "Supply the CA, client certificate and key, or set the TLS switch for your example. Lettuce needs at least one certificate."],
    ["Certificate file \"was not found\" / <code>No such file or directory</code> / <code>FileNotFoundException</code>",
     "Wrong working directory, or the file is not in <code>certs/</code>.",
     "Run from inside the example folder, check <code>ls -l certs/</code>, or set <code>REDIS_CA_CERT</code>, <code>REDIS_CLIENT_CERT</code> and <code>REDIS_CLIENT_KEY</code> to absolute paths."],
    ["<strong>Certificate invalid / expired:</strong> <code>certificate has expired</code>, <code>NotTimeValid</code>, <code>notAfter</code> in the past",
     "The server, client or CA certificate is past its end date (or its start date is in the future, or the machine clock is wrong).",
     "Run the <em>Check certificate dates</em> command below on all three files, and compare with <code>date</code>. Ask for a renewed certificate; fix the system clock if it is off."],
    ["<strong>Untrusted CA:</strong> <code>unable to get local issuer certificate</code>, <code>PKIX path building failed</code>, <code>UntrustedRoot</code>, <code>PartialChain</code>, <code>CERTIFICATE_VERIFY_FAILED</code>",
     "<code>ca.crt</code> is not the CA that signed the <em>server</em> certificate, or an intermediate CA is missing from the file.",
     "Run the live handshake test below. Get the correct CA from your Redis administrator. If there are intermediates, put the whole chain (intermediates, then root) in the CA file."],
    ["<strong>Hostname mismatch:</strong> <code>hostname mismatch</code>, <code>No subject alternative names matching</code>, <code>Hostname mismatch, certificate is not valid for</code>",
     "The host you connect to is not listed in the server certificate's Subject Alternative Names (for example you used an IP or an alias).",
     "Connect with a name listed in the certificate (see <em>Show the server certificate names</em> below), or ask for a certificate that includes your hostname."],
    ["Server rejects the client certificate: <code>bad certificate</code>, <code>unknown ca</code>, <code>certificate required</code>, <code>handshake failure</code>, connection reset right after connect",
     "The server does not trust the CA that signed <code>client.crt</code>, the client certificate is expired, or no client certificate was sent.",
     "Run <em>Check the client certificate against the CA</em>. Ask the Redis administrator which CA the database trusts for clients."],
    ["Private key problems: <code>key values mismatch</code>, <code>PEM lib</code>, <code>Could not read private key</code>, <code>InvalidKeySpecException</code>, <code>openssl pkcs12 failed</code>",
     "The key does not match the certificate, the file is not valid PEM, it is password-protected, or it is in the wrong format (Lettuce needs PKCS#8).",
     "Run <em>Check the key matches the certificate</em> and <em>Check the key format</em> below. Convert or decrypt the key if needed."],
    ["<code>wrong version number</code>, <code>packet length too long</code>, <code>SSL routines</code> error immediately",
     "You are connecting to a port that is not a TLS port (plain Redis port such as 6379).",
     "Use the database's TLS port (443 for an OpenShift route). Confirm <code>REDIS_PORT</code>."],
    ["Handshake closed or reset on port 443 with no certificate message",
     "The OpenShift route/ingress routes by SNI and the client did not send the right server name.",
     "Connect with the full route hostname (not an IP) so SNI is sent. Test with <code>openssl s_client -servername</code>."],
    ["<code>WRONGPASS</code>, <code>invalid username-password pair</code>, <code>NOAUTH Authentication required</code>, <code>AuthenticationError</code>",
     "TLS worked, but the username or password is wrong or missing.",
     "Check <code>REDIS_USERNAME</code> and <code>REDIS_PASSWORD</code>. Re-read the password from the secret and make sure there is no trailing newline or space."],
    ["Timeout / <code>Connection refused</code> / <code>Connect timed out</code> / <code>Timeout connecting to server</code>",
     "A firewall, VPN or network policy blocks the port, or the host/port is wrong.",
     "Run <code>nc -vz \"$REDIS_HOST\" \"$REDIS_PORT\"</code>. Check VPN, proxies and firewall rules."],
    ["<code>UnknownHostException</code>, <code>Name or service not known</code>, <code>nodename nor servname provided</code>",
     "The hostname does not resolve (typo, wrong DNS, VPN off).",
     "Run <code>nslookup \"$REDIS_HOST\"</code> and check the spelling and your DNS/VPN."],
]

# Diagnostic commands: [title, explanation, command, what to look for]
DIAGNOSTICS = [
    ["Set the variables once",
     "The commands below reuse the same environment variables as the examples. Run them from the example folder.",
     'export REDIS_HOST="your-db.example.com"\nexport REDIS_PORT="443"',
     "No output."],
    ["Check the files and the key format",
     "Confirms the files exist and shows what type of private key you have.",
     "ls -l certs/\nhead -1 certs/client.key",
     "<code>-----BEGIN PRIVATE KEY-----</code> = PKCS#8 (works everywhere). <code>-----BEGIN RSA PRIVATE KEY-----</code> or <code>BEGIN EC PRIVATE KEY</code> = traditional format (convert for Lettuce). <code>-----BEGIN ENCRYPTED PRIVATE KEY-----</code> = password-protected (decrypt first)."],
    ["Check certificate dates (is it expired?)",
     "Shows who the certificate belongs to, who issued it and when it is valid.",
     "openssl x509 -in certs/client.crt -noout -subject -issuer -dates\nopenssl x509 -in certs/ca.crt -noout -subject -issuer -dates\nopenssl x509 -in certs/client.crt -noout -checkend 0",
     "Today's date must be between <code>notBefore</code> and <code>notAfter</code>. The last command prints <code>Certificate will expire</code> if it has already expired."],
    ["Check the client certificate against the CA",
     "Verifies that <code>client.crt</code> was signed by <code>ca.crt</code>.",
     "openssl verify -CAfile certs/ca.crt certs/client.crt",
     "<code>certs/client.crt: OK</code>. Errors such as <code>unable to get local issuer certificate</code> or <code>certificate has expired</code> point to the cause. If your client certificate comes from a different CA than the server's, this check can fail even though the setup is fine - ask your administrator."],
    ["Check the key matches the certificate",
     "A certificate and key belong together only if their public keys are identical.",
     "openssl x509 -in certs/client.crt -noout -pubkey | openssl sha256\nopenssl pkey -in certs/client.key -pubout | openssl sha256",
     "Both lines must print the <strong>same</strong> hash. If they differ, you have the wrong key or the wrong certificate."],
    ["Test the live TLS handshake",
     "Connects to the server with your three files, exactly like the application does, without any Redis client code.",
     'openssl s_client -connect "$REDIS_HOST:$REDIS_PORT" -servername "$REDIS_HOST" \\\n  -CAfile certs/ca.crt -cert certs/client.crt -key certs/client.key \\\n  -verify_hostname "$REDIS_HOST" </dev/null',
     "Look for <code>Verify return code: 0 (ok)</code> near the end. Common failures: <code>20 unable to get local issuer certificate</code> (wrong CA), <code>10 certificate has expired</code>, <code>alert bad certificate</code> / <code>unknown ca</code> (server rejected the client certificate). <code>-verify_hostname</code> needs OpenSSL 1.1+; drop it if your version does not support it."],
    ["Show the server certificate names",
     "Lists the hostnames the server certificate is valid for and its dates.",
     'openssl s_client -connect "$REDIS_HOST:$REDIS_PORT" -servername "$REDIS_HOST" </dev/null 2>/dev/null \\\n  | openssl x509 -noout -subject -issuer -dates -text | grep -E "Subject:|Issuer:|Not |DNS:"',
     "Your <code>REDIS_HOST</code> must match one of the <code>DNS:</code> entries (a <code>*.example.com</code> wildcard covers one label only)."],
    ["Check the network",
     "Separates network and DNS problems from certificate problems.",
     'nslookup "$REDIS_HOST"\nnc -vz "$REDIS_HOST" "$REDIS_PORT"',
     "The name must resolve, and <code>nc</code> must report <code>succeeded</code> or <code>open</code>."],
    ["Test Redis outside your application",
     "If you have <code>redis-cli</code> 6.2+ this confirms TLS and login together. The password is passed via an environment variable so it stays out of your shell history.",
     'REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" --tls \\\n  --cacert certs/ca.crt --cert certs/client.crt --key certs/client.key \\\n  --sni "$REDIS_HOST" --user default PING',
     "<code>PONG</code>. If this works but the sample fails, the problem is in how the sample is run (paths, variables, key format). If this also fails, fix the certificates, network or credentials first."],
    ["Convert or decrypt the private key",
     "Use when the key is in the traditional format (Lettuce needs PKCS#8) or is password-protected.",
     "# convert to unencrypted PKCS#8\nopenssl pkcs8 -topk8 -nocrypt -in certs/client.key -out certs/client-pkcs8.key\n\n# remove a passphrase (you will be asked for it)\nopenssl pkey -in certs/client.key -out certs/client-decrypted.key\n\n# then point the example at the new file\nexport REDIS_CLIENT_KEY=\"certs/client-pkcs8.key\"",
     "Re-run the example. Keep the new key file protected (<code>chmod 600</code>) and delete the copies you do not need."],
]

# [symptom, likely cause, what to do] - specific to each framework's output
FW_ERRORS = {
    "Jedis": [
        ["<code>Client certificate was not found: /full/path</code> (or CA / key)",
         "The app looked in that exact absolute path and found nothing.",
         "Run <code>mvn exec:java</code> from the <code>Jedis</code> folder, or set the <code>REDIS_*</code> path variables."],
        ["<code>openssl pkcs12 failed with exit code ...</code>",
         "The app runs <code>openssl</code> to build a temporary keystore, and it failed: key and certificate do not match, key is encrypted, a file is not PEM, or <code>openssl</code> is not installed.",
         "Read the OpenSSL message printed under it, then run the key/certificate checks above and <code>openssl version</code>."],
        ["<code>No certificates were found in certs/ca.crt</code>",
         "The CA file is empty or not PEM.",
         "Open the file: it must contain <code>-----BEGIN CERTIFICATE-----</code>."],
        ["<code>javax.net.ssl.SSLHandshakeException: PKIX path building failed ... unable to find valid certification path</code>",
         "The server certificate is not signed by the CA you supplied.",
         "Use the correct CA file; include intermediates."],
        ["<code>SSLHandshakeException: No subject alternative names matching ...</code>",
         "Hostname is not in the server certificate.",
         "Use a hostname listed in the certificate."],
        ["<code>Received fatal alert: bad_certificate</code> or <code>certificate_unknown</code>",
         "The server rejected your client certificate.",
         "Check the client certificate against the CA and its dates."],
        ["<code>JedisConnectionException</code> with <code>Connect timed out</code> or <code>Read timed out</code>",
         "Network blocked, or wrong host/port. The sample uses 5-second timeouts.",
         "Run the network checks above."],
        ["<code>JedisAccessControlException</code> / <code>WRONGPASS</code> / <code>NOAUTH</code>",
         "Wrong or missing username/password.",
         "Check <code>REDIS_USERNAME</code> and <code>REDIS_PASSWORD</code>."],
        ["<code>release version 17 not supported</code> or <code>UnsupportedClassVersionError</code>",
         "Java older than 17.",
         "Run <code>java -version</code> and <code>mvn -version</code>; install JDK 17+ and point <code>JAVA_HOME</code> to it."],
        ["<code>Invalid REDIS_PORT</code> / <code>NumberFormatException</code>",
         "The port is not a number.",
         "Use digits only, for example <code>443</code>."],
    ],
    "Lettuce": [
        ["<code>RedisConnectionException: Unable to connect to host:443</code>",
         "Generic wrapper. The real reason is in the <code>Caused by:</code> lines below it.",
         "Scroll to the cause: a <code>SSLHandshakeException</code> means certificates, a timeout means network."],
        ["<code>Caused by: ... PKIX path building failed</code> / <code>unable to find valid certification path</code>",
         "Server certificate not signed by the supplied CA.",
         "Use the correct CA file; include intermediates."],
        ["<code>InvalidKeySpecException</code>, <code>algid parse error</code>, <code>Could not read private key</code>, <code>IllegalArgumentException: ... PKCS8</code>",
         "Lettuce needs an unencrypted <strong>PKCS#8</strong> key; yours is in the traditional (<code>BEGIN RSA PRIVATE KEY</code>) format or encrypted.",
         "Convert it: <code>openssl pkcs8 -topk8 -nocrypt -in certs/client.key -out certs/client-pkcs8.key</code> and set <code>REDIS_CLIENT_KEY</code>."],
        ["<code>RedisCommandTimeoutException: Command timed out after 10 second(s)</code>",
         "Connection opened but the command did not complete in the sample's 10-second timeout.",
         "Check network latency, firewall and server load."],
        ["<code>RedisCommandExecutionException: WRONGPASS</code> or <code>NOAUTH</code>",
         "Wrong or missing credentials.",
         "Check <code>REDIS_USERNAME</code> and <code>REDIS_PASSWORD</code>. The sample sends a username only if <code>REDIS_USERNAME</code> is set."],
        ["<code>java.net.UnknownHostException</code>",
         "Hostname does not resolve.",
         "Check <code>REDIS_HOST</code>, DNS and VPN."],
        ["<code>release version 17 not supported</code>",
         "Java older than 17.",
         "Install JDK 17+ and check <code>mvn -version</code>."],
    ],
    "StackExchange": [
        ["<code>TLS validation failed: the server certificate was not signed by the configured CA.</code> followed by lines like <code>UntrustedRoot</code>, <code>PartialChain</code>, <code>NotTimeValid</code>",
         "The sample validates the server against your CA file and prints the chain status. These lines tell you why.",
         "<code>UntrustedRoot</code>/<code>PartialChain</code> = wrong or incomplete CA. <code>NotTimeValid</code> = expired. Use the diagnostics below."],
        ["<code>TLS validation failed: server certificate hostname mismatch.</code>",
         "<code>REDIS_HOST</code> is not in the server certificate.",
         "Use a hostname listed in the certificate."],
        ["<code>TLS validation failed: the server did not provide a certificate.</code> / <code>server certificate is unavailable.</code>",
         "The connection was not a real TLS session (wrong port or a proxy).",
         "Confirm the TLS port and test with <code>openssl s_client</code>."],
        ["<code>Redis connection failed: It was not possible to connect to the redis server(s)</code>",
         "General connection failure. The messages printed just above it say whether it was TLS, network or authentication.",
         "Read the lines above, then use the checklist."],
        ["<code>Client certificate was not found.</code> (<code>FileNotFoundException</code>, with the full path)",
         "The file is not at that absolute path.",
         "Run <code>dotnet run</code> from the <code>StackExchange</code> folder or set the path variables."],
        ["<code>openssl pkcs12 failed</code> / an <code>InvalidOperationException</code> mentioning OpenSSL, or <code>Win32Exception</code>",
         "OpenSSL is missing from <code>PATH</code>, or it could not combine your key and certificate (mismatch, encrypted key, not PEM).",
         "Run <code>openssl version</code>, then the key and certificate checks."],
        ["<code>No certificates were found in ...</code>",
         "The CA file is empty or not PEM.",
         "It must contain <code>-----BEGIN CERTIFICATE-----</code>."],
        ["<code>WRONGPASS</code> / <code>NOAUTH</code> (<code>RedisServerException</code>)",
         "Wrong or missing credentials.",
         "Check <code>REDIS_USERNAME</code> and <code>REDIS_PASSWORD</code>."],
        ["<code>Timeout performing PING</code>",
         "Connected but the server did not answer within 5 seconds.",
         "Check network latency and server load."],
        ["<code>Invalid REDIS_PORT value</code>",
         "The port is not a number.",
         "Use digits only, for example <code>443</code>."],
        ["<code>The framework 'Microsoft.NETCore.App', version '7.0.0' was not found</code>",
         ".NET 7 runtime is not installed.",
         "Run <code>dotnet --list-sdks</code> and install .NET SDK 7.0 or later."],
    ],
    "Python": [
        ["<code>Connection failed: [SSL: CERTIFICATE_VERIFY_FAILED] ... unable to get local issuer certificate</code>",
         "The CA file is not the one that signed the server certificate (the sample requires verification).",
         "Use the correct CA; include intermediates."],
        ["<code>CERTIFICATE_VERIFY_FAILED ... CA cert does not include key usage extension</code> (works with Java/.NET, or with an older Python)",
         "Python 3.13 and later check certificates strictly, and your CA certificate has no Key Usage extension. Older Python versions, Java and .NET do not check this.",
         "The sample now relaxes this check by default (set <code>REDIS_SSL_STRICT=1</code> to enforce it). The proper fix is to re-issue the CA with <code>keyUsage = keyCertSign, cRLSign</code>. Check yours with <code>openssl x509 -in certs/ca.crt -noout -text | grep -A1 \"Key Usage\"</code>."],
        ["<code>CERTIFICATE_VERIFY_FAILED ... certificate has expired</code>",
         "A certificate in the chain has expired.",
         "Run the date checks."],
        ["<code>CERTIFICATE_VERIFY_FAILED ... Hostname mismatch, certificate is not valid for '...'</code>",
         "<code>REDIS_HOST</code> is not in the server certificate.",
         "Use a hostname listed in the certificate."],
        ["<code>ssl.SSLError: [SSL] PEM lib</code> or <code>key values mismatch</code>",
         "<code>client.key</code> does not match <code>client.crt</code>, or one of them is not valid PEM.",
         "Run the key/certificate match check."],
        ["<code>[SSL: TLSV1_ALERT_UNKNOWN_CA]</code> or <code>SSLV3_ALERT_BAD_CERTIFICATE</code>",
         "The server rejected your client certificate.",
         "Check the client certificate's CA and dates."],
        ["<code>FileNotFoundError: [Errno 2] No such file or directory</code>",
         "A certificate path is wrong. Default paths are relative to <code>python_conn.py</code>.",
         "Check <code>certs/</code> next to the script or set the path variables."],
        ["<code>ModuleNotFoundError: No module named 'redis'</code>",
         "The virtual environment is not active or the package is not installed.",
         "<code>source .venv/bin/activate</code> then <code>python -m pip install redis</code>."],
        ["<code>Connection failed: WRONGPASS invalid username-password pair</code> / <code>Authentication required.</code>",
         "Wrong or missing credentials.",
         "Check <code>REDIS_USERNAME</code> and <code>REDIS_PASSWORD</code>."],
        ["<code>Connection failed: Timeout connecting to server</code> / <code>Connection refused</code>",
         "Network blocked or wrong host/port.",
         "Run the network checks."],
        ["<code>Error ... connecting to host:443. nodename nor servname provided</code> (or <code>Name or service not known</code>)",
         "Hostname does not resolve.",
         "Check <code>REDIS_HOST</code>, DNS and VPN."],
        ["<code>ValueError: invalid literal for int()</code>",
         "<code>REDIS_PORT</code> is not a number.",
         "Use digits only, for example <code>443</code>."],
    ],
}
